"""added Selections

Revision ID: 08227e7b998b
Revises: 3d4cc4abdc47
Create Date: 2023-12-18 09:44:11.747139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08227e7b998b'
down_revision = '3d4cc4abdc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_selections_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selections'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selections')
    # ### end Alembic commands ###
